name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          python -m venv .venv
          source .venv/bin/activate
          if [ -f pyproject.toml ]; then
            uv pip install -e ".[dev]"
          fi

      - name: Run Bandit Security Scan
        uses: PyCQA/bandit-action@v2
        with:
          targets: "src/"
          ini: ".bandit"
        continue-on-error: true

      - name: Upload SARIF results to GitHub Security tab
        if: github.ref == 'refs/heads/main'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-results.sarif
        continue-on-error: true

      - name: Upload SARIF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandit-sarif-results
          path: bandit-results.sarif
          retention-days: 30
        continue-on-error: true
